### PR TITLE
Stream the request body

### PR DESCRIPTION
**Pull request by flintinatux**
dilbert

This has been suggested for a while, and now that we finally have a proper use-case for it, it's time to make it happen.  When I first wrote `paperplane`, I buffered the body mostly out of convenience.  At least it seemed that way at the time.  But the change doesn't actually require much to migrate your app, so I'm wishing I had just done it this way originally.

**What this PR does:**
1.  The `req.body` is now a `Readable` stream.
2.  `parseJson` now returns a `Promise`, since it must buffer that stream.
3.  `bufferBody` is a thing, if you liked the original behavior and rely on it for some reason.

Numbers 1 and 2 above denote a breaking change, so this will push us to `v3`.  🎉

## to review:
- [ ] Read the code.
- [ ] Read the new docs.
- [ ] Follow the migration guide to upgrade an existing app.
- [ ] Wait for the green light from Travis.

### CODE REVIEW

**Comment by flintinatux** [comment]
> The examples show using `parseJson` compose at the app level. `composeP(app, parseJson)`. Is there a route-level way of doing this? Using `parseJson` for all routes _except_ the ones we want to stream?

@mgreystone, yep, like this:
```js
const app = routes({
  '/parse-this':  composeP(handler1, parseJson),
  '/but-not-this':  handler2
})
```
However, I should note that `parseJson` only does its thing if the body has `content-length` and the `content-type` is `application/json`.  All other requests it just ignores.  So in most cases you can just put it at the top.  If you want to parse json with a separate streaming library for some endpoints, then the example above should work for you.

**Comment by mgreystone** [comment]
Can we maybe make `parseJson` _not_ do it's thing if `Transfer-Encoding: chunked`?

**Comment by flintinatux** [comment]
`transfer-encoding` looks to me like a response header, not a request one.  Am I wrong?

**Comment by mgreystone** [comment]
I thought it was both, like `Content-Length`... 🤷‍♂

**Comment by flintinatux** [comment]
I think you're right.  According to Wikipedia (the fount of all knowledge):
> If a Transfer-Encoding field with a value of "chunked" is specified in an HTTP message (either a request sent by a client or the response from the server)...

But help me understand why `transfer-encoding: chunked` should always mean "don't buffer and parse this as one piece".  It seems more like a transport directive, not "what you do with it on your end" directive.

**Comment by mgreystone** [comment]
Yeah, i suppose that fair. My train of though is that the client is _telling_ the server that it's going to send the request in chunks, and that it should be streamed. But i guess it could also be buffered. 🤦‍♂ Okay, i'm sold.

**Comment by flintinatux** [comment]
squirrel

**Pull request merged**
